### ISSUE TITLE
Unpickling stack underflow

### ISSUE THREAD

**Issue by westdev9** [ProGamerGov/neural-style-pt#83]
When I try to run models/download_models.py, I get the following error: 
'''
Downloading the VGG-19 model
Traceback (most recent call last):
  File "models/download_models.py", line 10, in <module>
    sd = load_url("https://web.eecs.umich.edu/~justincj/models/vgg19-d01eb7cb.pth")
  File "/home/wroge/anaconda3/envs/neural-style-env/lib/python3.8/site-packages/torch/hub.py", line 559, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/wroge/anaconda3/envs/neural-style-env/lib/python3.8/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/wroge/anaconda3/envs/neural-style-env/lib/python3.8/site-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: unpickling stack underflow
'''

**Comment by ProGamerGov** [comment]
@West102 What version of PyTorch are you using?

**Comment by westdev9** [comment]
@ProGamerGov I am using PyTorch version 1.7.0 and Python 3.8.5

**Comment by ProGamerGov** [comment]
@West102 I can't seem to reproduce the issue with PyTorch 1.7.0, though I was using Python 3.6. I also didn't see anything in the change notes that would cause this issue. There's various reports of similar issues on the PyTorch Github page, but no mention of the cause. Have you tried reinstalling PyTorch? Can you reliably reproduce the error?


I also have copies of the models (with the correct changes) available for download here: https://drive.google.com/drive/folders/1OGKfoIehp2MiJL2Iq_8VMTy76L6waGC8
